export type IndustryCard = {
  title: string;
  body: string;
  icon: string;
  tags?: string[];
};

export type IndustryPageConfig = {
  slug: string;
  shortName: string;
  metadataTitle: string;
  description: string;
  theme: string;
  eyebrow: string;
  heroLead: string;
  heroAccent: string;
  heroBody: string;
  heroLabel: string;
  heroSignals: string[];
  heroOutcome: string;
  challengeTitle: string;
  challengeAccent: string;
  challengeBody: string;
  challenges: IndustryCard[];
  servicesTitle: string;
  servicesAccent: string;
  servicesBody: string;
  services: IndustryCard[];
  workflowTitle: string;
  workflowAccent: string;
  workflowBody: string;
  workflow: Array<{ title: string; body: string }>;
  opportunitiesTitle: string;
  opportunitiesAccent: string;
  opportunitiesBody: string;
  opportunities: IndustryCard[];
  proofTitle: string;
  proofAccent: string;
  proofBody: string;
  proof: Array<{ kicker: string; title: string; body: string }>;
  audiences: string[];
  faqs: Array<{ question: string; answer: string }>;
  related: Array<{ href: string; label: string; description: string }>;
  ctaEyebrow: string;
  ctaTitle: string;
  ctaAccent: string;
  ctaBody: string;
};

const sharedRelated = [
  { href: "/seo-services", label: "SEO services", description: "Build durable visibility across Google and AI search." },
  { href: "/ppc-management", label: "PPC management", description: "Capture demand while organic visibility develops." },
  { href: "/web-development", label: "Web development", description: "Turn the website into a faster conversion system." },
  { href: "/case-studies", label: "Case studies", description: "Review the work behind our recommendations." },
];

export const industryPages: Record<string, IndustryPageConfig> = {
  "dental-medical-marketing": {
    slug: "dental-medical-marketing",
    shortName: "Dental & Medical Marketing",
    metadataTitle: "Dental & Medical Marketing Services | Rank It Globally",
    description: "Search, content, paid media, and conversion systems that help dental and medical practices earn trust and generate more appointment opportunities.",
    theme: "healthcare",
    eyebrow: "Healthcare growth systems",
    heroLead: "Be easier to find",
    heroAccent: "before patients choose a practice.",
    heroBody: "We connect local search, procedure content, paid campaigns, reviews, and a clearer booking journey so prospective patients can understand and trust the practice.",
    heroLabel: "Patient discovery path",
    heroSignals: ["Local intent", "Clinical trust", "Appointment clarity"],
    heroOutcome: "A clearer path to an appointment",
    challengeTitle: "Why good practices can remain",
    challengeAccent: "hard to discover.",
    challengeBody: "Healthcare decisions happen quickly and carry a high trust threshold. Visibility, credibility, and the booking experience need to support one another.",
    challenges: [
      { icon: "pin", title: "Near-me results are concentrated", body: "A small group of well-built profiles and local pages often receive most high-intent attention." },
      { icon: "reviews", title: "Reviews shape the shortlist", body: "Patients compare recency, relevance, and response quality before they call." },
      { icon: "mobile", title: "Mobile is the first consultation", body: "Slow pages and unclear booking actions create doubt before the practice can explain its value." },
      { icon: "ai", title: "Search answers are changing", body: "AI summaries increasingly reward specific, structured, trustworthy information." },
      { icon: "content", title: "Procedure pages lack depth", body: "Thin pages rarely answer the questions that influence a patient decision." },
      { icon: "shield", title: "Trust must be handled carefully", body: "Claims, patient information, and advertising language need thoughtful governance." },
    ],
    servicesTitle: "Marketing built around",
    servicesAccent: "patient decisions.",
    servicesBody: "Each service supports a stage between first discovery and a completed appointment request.",
    services: [
      { icon: "pin", title: "Local search visibility", body: "Strengthen location signals, profile completeness, and service-area relevance.", tags: ["Maps", "GBP", "Locations"] },
      { icon: "content", title: "Procedure content", body: "Create useful pages that explain treatments, candidacy, expectations, and next steps.", tags: ["Service pages", "FAQs", "Internal links"] },
      { icon: "ads", title: "Intent-led advertising", body: "Build search and social campaigns around the services the practice wants to grow.", tags: ["Google Ads", "Meta", "Landing pages"] },
      { icon: "mobile", title: "Appointment-ready websites", body: "Improve speed, readability, trust cues, and booking actions across devices.", tags: ["UX", "CRO", "Performance"] },
      { icon: "shield", title: "Authority and trust", body: "Present credentials, clinicians, policies, and evidence in a clear, responsible format.", tags: ["E-E-A-T", "Profiles", "Schema"] },
      { icon: "reviews", title: "Review systems", body: "Create a consistent, ethical process for earning and responding to patient feedback.", tags: ["Reputation", "Responses", "Insights"] },
    ],
    workflowTitle: "From visibility review to",
    workflowAccent: "a connected patient journey.",
    workflowBody: "We prioritize foundational blockers first, then expand the channels that can create sustainable demand.",
    workflow: [
      { title: "Audit discovery", body: "Review technical health, local presence, patient intent, and booking friction." },
      { title: "Clarify priorities", body: "Map procedures, locations, audiences, and responsible messaging." },
      { title: "Build the foundation", body: "Improve pages, profiles, tracking, and conversion paths." },
      { title: "Grow useful coverage", body: "Publish, promote, test, and refine based on qualified demand." },
    ],
    opportunitiesTitle: "One practice, several",
    opportunitiesAccent: "paths to discovery.",
    opportunitiesBody: "The strongest mix depends on location, procedure economics, capacity, and the questions patients ask before booking.",
    opportunities: [
      { icon: "search", title: "Organic search", body: "Answer procedure and condition-led queries with useful clinical context." },
      { icon: "pin", title: "Local discovery", body: "Support maps visibility with consistent profiles, locations, and reviews." },
      { icon: "ads", title: "Paid demand", body: "Reach patients searching now while longer-term authority develops." },
      { icon: "cro", title: "Conversion clarity", body: "Make calls, forms, and appointment steps easy to understand and complete." },
    ],
    proofTitle: "Proof should feel like",
    proofAccent: "clarity, not hype.",
    proofBody: "We report on what changed, what visitors did next, and which opportunities deserve further investment.",
    proof: [
      { kicker: "Visibility", title: "Track meaningful discovery", body: "Measure relevant search impressions, profile actions, and landing-page engagement." },
      { kicker: "Experience", title: "Find appointment friction", body: "Review mobile behavior, form completion, and the clarity of each next step." },
      { kicker: "Learning", title: "Improve with evidence", body: "Use search terms, patient questions, and campaign quality to guide the next iteration." },
    ],
    audiences: ["Dental practices", "Specialists", "Medical clinics", "Wellness providers", "Multi-location groups", "New practices"],
    faqs: [
      { question: "Can you market both dental and medical practices?", answer: "Yes. The channel mix may be similar, but the content, trust signals, patient journey, and advertising constraints are planned around the specific practice and services." },
      { question: "Do you guarantee first position in Google Maps?", answer: "No responsible agency can guarantee a fixed ranking. We improve the profile, website, local relevance, reviews, and technical signals that influence visibility." },
      { question: "Can you help a multi-location practice?", answer: "Yes. We can structure location pages, profile ownership, citation consistency, reporting, and content so each location has a clear local footprint." },
      { question: "How do you handle healthcare claims and privacy?", answer: "We use careful language, avoid unsupported promises, and work with your team on approval and privacy requirements. Legal or clinical compliance remains the practice's responsibility." },
      { question: "Should we use SEO or paid ads first?", answer: "That depends on urgency, capacity, competition, and existing visibility. Paid search can capture immediate demand while SEO builds a more durable discovery system." },
      { question: "What should a healthcare marketing report include?", answer: "It should connect visibility and campaign data to meaningful actions such as qualified calls, appointment requests, and high-intent page engagement." },
    ],
    related: sharedRelated,
    ctaEyebrow: "Start with a clearer diagnosis",
    ctaTitle: "See where patient demand is",
    ctaAccent: "getting lost.",
    ctaBody: "Request a free audit and we will identify the search, website, trust, and conversion opportunities worth addressing first.",
  },
  "ecommerce-marketing": {
    slug: "ecommerce-marketing",
    shortName: "E-Commerce Marketing",
    metadataTitle: "E-Commerce Marketing Services | Rank It Globally",
    description: "SEO, paid media, content, retention, and conversion strategy for e-commerce brands that want more value from existing traffic and sustainable demand.",
    theme: "commerce",
    eyebrow: "Full-funnel commerce growth",
    heroLead: "Grow revenue without",
    heroAccent: "renting every visit.",
    heroBody: "We connect product discovery, category SEO, paid acquisition, conversion improvements, and retention so growth does not depend on one expensive channel.",
    heroLabel: "Commerce growth loop",
    heroSignals: ["Discover", "Decide", "Return"],
    heroOutcome: "More value from every visit",
    challengeTitle: "Why stores plateau",
    challengeAccent: "after the launch.",
    challengeBody: "A polished storefront is only the beginning. Sustainable growth needs discoverable merchandising, efficient acquisition, and fewer leaks between product view and repeat purchase.",
    challenges: [
      { icon: "ads", title: "Paid acquisition gets expensive", body: "Rising costs expose brands that lack organic demand and retention." },
      { icon: "search", title: "Categories do not rank", body: "Product grids without useful context struggle to match broader shopping intent." },
      { icon: "cart", title: "Checkout friction compounds", body: "Small mobile, shipping, or trust issues can weaken every campaign." },
      { icon: "analytics", title: "Shopping spend lacks focus", body: "Weak feeds and mixed intent can direct budget toward low-value clicks." },
      { icon: "content", title: "Content sits outside commerce", body: "Guides often fail to connect education with relevant collections and products." },
      { icon: "mobile", title: "Mobile buying feels harder", body: "Slow pages and dense interfaces create unnecessary hesitation." },
    ],
    servicesTitle: "A growth system for",
    servicesAccent: "the whole storefront.",
    servicesBody: "We improve how shoppers find, evaluate, buy, and return to the brand.",
    services: [
      { icon: "search", title: "Product and category SEO", body: "Align architecture, copy, filters, and internal links with how shoppers search.", tags: ["Collections", "Products", "Technical SEO"] },
      { icon: "ads", title: "Paid acquisition", body: "Use search, shopping, and social campaigns with clearer commercial intent.", tags: ["Google", "Meta", "TikTok"] },
      { icon: "cro", title: "Conversion optimization", body: "Improve product pages, navigation, cart confidence, and checkout transitions.", tags: ["UX", "Testing", "Merchandising"] },
      { icon: "content", title: "Buying guides", body: "Create useful comparisons and education that lead naturally into products.", tags: ["Editorial", "Discovery", "Internal links"] },
      { icon: "community", title: "Lifecycle growth", body: "Strengthen repeat purchase with clearer segmentation, education, and offers.", tags: ["Email", "Retention", "Loyalty"] },
      { icon: "analytics", title: "Commerce measurement", body: "Connect channel performance with product margin, quality, and repeat behavior.", tags: ["GA4", "Feeds", "Reporting"] },
    ],
    workflowTitle: "From store audit to",
    workflowAccent: "compounding growth.",
    workflowBody: "We fix blockers before scaling spend, then use real shopper behavior to decide what to expand.",
    workflow: [
      { title: "Map the funnel", body: "Review traffic quality, merchandising, conversion, and retention signals." },
      { title: "Fix the leaks", body: "Prioritize technical, product-page, navigation, and tracking issues." },
      { title: "Expand demand", body: "Build search coverage, campaigns, creative, and commercial content." },
      { title: "Learn and compound", body: "Refine around stronger products, audiences, and purchase paths." },
    ],
    opportunitiesTitle: "Balance acquisition with",
    opportunitiesAccent: "owned demand.",
    opportunitiesBody: "The goal is not to remove paid media. It is to make every channel work harder because the store converts and retains attention better.",
    opportunities: [
      { icon: "search", title: "Category discovery", body: "Capture shoppers before they know a specific product name." },
      { icon: "ads", title: "Intent-based campaigns", body: "Match creative and landing pages to buying stage and product economics." },
      { icon: "cro", title: "Purchase confidence", body: "Answer fit, delivery, returns, and trust questions where decisions happen." },
      { icon: "community", title: "Repeat value", body: "Give customers a reason to return beyond another discount." },
    ],
    proofTitle: "Measure the business,",
    proofAccent: "not vanity traffic.",
    proofBody: "Useful reporting connects channels with product-level behavior, conversion quality, and repeat value.",
    proof: [
      { kicker: "Demand", title: "See what shoppers want", body: "Use queries, feeds, and product engagement to reveal commercial demand." },
      { kicker: "Friction", title: "Find where intent drops", body: "Review the path from landing page through product, cart, and checkout." },
      { kicker: "Value", title: "Prioritize profitable growth", body: "Consider margin, return behavior, and repeat purchase alongside revenue." },
    ],
    audiences: ["DTC brands", "Retailers", "B2B commerce", "Subscription stores", "Marketplaces", "Growing catalogs"],
    faqs: [
      { question: "Do you work with Shopify and WooCommerce?", answer: "Yes. We plan around the store's platform, theme, app stack, analytics, and development constraints rather than forcing the same checklist onto every store." },
      { question: "Should an e-commerce brand start with SEO or ads?", answer: "It depends on demand, margin, seasonality, and how quickly the store needs feedback. Often the best plan fixes conversion issues first, then uses paid and organic channels together." },
      { question: "Can you improve an existing store without redesigning it?", answer: "Often, yes. We can prioritize navigation, collection content, product pages, speed, tracking, and conversion improvements before deciding whether a larger redesign is justified." },
      { question: "How do you measure e-commerce marketing?", answer: "We look beyond clicks to purchase behavior, product performance, conversion rate, acquisition quality, and repeat value where reliable data is available." },
      { question: "Can you manage Google Shopping and paid social?", answer: "Yes. Campaign structure, feed quality, creative, landing pages, and measurement should work as one acquisition system." },
      { question: "Will SEO interfere with product merchandising?", answer: "It should support merchandising. Good e-commerce SEO helps shoppers and search engines understand categories without turning the store into a wall of keyword copy." },
    ],
    related: sharedRelated,
    ctaEyebrow: "Start with the whole funnel",
    ctaTitle: "Find what is limiting",
    ctaAccent: "store growth.",
    ctaBody: "Request a free audit and we will review discovery, paid acquisition, storefront friction, and the highest-value next steps.",
  },
  "home-services-marketing": {
    slug: "home-services-marketing",
    shortName: "Home Services Marketing",
    metadataTitle: "Home Services Marketing | Rank It Globally",
    description: "Local search, paid media, review, and conversion systems that help home service businesses earn more direct calls and quote requests.",
    theme: "home-services",
    eyebrow: "Own more local demand",
    heroLead: "Turn nearby searches into",
    heroAccent: "direct calls and quotes.",
    heroBody: "We help contractors reduce dependence on lead marketplaces by improving maps visibility, service-area pages, reviews, paid search, and the website's path to contact.",
    heroLabel: "Local lead system",
    heroSignals: ["Service", "Area", "Urgency"],
    heroOutcome: "More direct customer opportunities",
    challengeTitle: "Why contractors keep paying for",
    challengeAccent: "leads they should own.",
    challengeBody: "Local demand is fragmented across maps, ads, service pages, reviews, and urgent mobile searches. Weakness in one area raises acquisition costs everywhere else.",
    challenges: [
      { icon: "ads", title: "Lead marketplace dependence", body: "Shared leads are expensive and keep the customer relationship with a third party." },
      { icon: "pin", title: "Map Pack concentration", body: "Incomplete local signals make it difficult to compete in high-intent nearby searches." },
      { icon: "reviews", title: "Competitors look safer", body: "A stronger volume and cadence of reviews can decide the call before price is discussed." },
      { icon: "mobile", title: "Emergency intent is lost", body: "Slow mobile pages and buried phone actions are costly when customers need help now." },
      { icon: "content", title: "Service areas are unclear", body: "One generic location page rarely supports the towns and services a contractor actually covers." },
      { icon: "profile", title: "Profiles are incomplete", body: "Categories, services, photos, updates, and conversion links often lack consistency." },
    ],
    servicesTitle: "Local visibility built for",
    servicesAccent: "service businesses.",
    servicesBody: "The system connects where you work, what you do, and why a nearby customer should contact you.",
    services: [
      { icon: "pin", title: "Map Pack visibility", body: "Improve profile completeness, relevance, reviews, and the connected website signals.", tags: ["GBP", "Maps", "Local pages"] },
      { icon: "content", title: "Service-area pages", body: "Build useful coverage for priority services and the areas the team can realistically serve.", tags: ["Cities", "Services", "Internal links"] },
      { icon: "shield", title: "Local Services Ads", body: "Support eligibility, lead quality review, and the experience after a customer clicks or calls.", tags: ["LSA", "Trust", "Lead quality"] },
      { icon: "reviews", title: "Review momentum", body: "Create a repeatable process for requesting, monitoring, and responding to feedback.", tags: ["Reputation", "Responses", "Insights"] },
      { icon: "cro", title: "Call and form conversion", body: "Make urgent and planned service requests easier to complete on mobile.", tags: ["Calls", "Forms", "UX"] },
      { icon: "ads", title: "Paid search", body: "Capture priority services while local and organic visibility develops.", tags: ["Google Ads", "Landing pages", "Tracking"] },
    ],
    workflowTitle: "From scattered listings to",
    workflowAccent: "a local demand engine.",
    workflowBody: "We establish service-area clarity first, then expand the channels that can produce direct, qualified opportunities.",
    workflow: [
      { title: "Map the territory", body: "Review services, locations, seasonality, capacity, and current lead sources." },
      { title: "Fix local foundations", body: "Align profiles, website pages, citations, reviews, and tracking." },
      { title: "Capture active demand", body: "Improve pages and campaigns for urgent and planned service searches." },
      { title: "Strengthen the system", body: "Use lead quality and search behavior to refine areas, offers, and budgets." },
    ],
    opportunitiesTitle: "Different jobs need",
    opportunitiesAccent: "different discovery paths.",
    opportunitiesBody: "Emergency work, large planned projects, maintenance, and repeat services each require a different balance of maps, ads, content, and follow-up.",
    opportunities: [
      { icon: "pin", title: "Nearby demand", body: "Show relevance where customers compare providers in maps." },
      { icon: "ads", title: "Urgent searches", body: "Use paid channels for high-priority services and immediate demand." },
      { icon: "content", title: "Planned projects", body: "Answer cost, process, timing, and service-area questions before the quote." },
      { icon: "cro", title: "Direct response", body: "Make the phone call or estimate request obvious on every device." },
    ],
    proofTitle: "Better visibility is only useful",
    proofAccent: "when lead quality improves.",
    proofBody: "We review which services, areas, and channels create conversations the team actually wants to handle.",
    proof: [
      { kicker: "Coverage", title: "See where you are visible", body: "Compare profile, page, and campaign coverage across priority service areas." },
      { kicker: "Response", title: "Connect demand to action", body: "Track qualified calls, forms, and the landing pages that created them." },
      { kicker: "Capacity", title: "Grow at a workable pace", body: "Adjust service and geographic emphasis around the team's real capacity." },
    ],
    audiences: ["Plumbers", "HVAC", "Roofing", "Painters", "Electricians", "Cleaning companies", "Landscapers", "Auto services"],
    faqs: [
      { question: "Can you help us rank in more than one city?", answer: "Yes, when the business genuinely serves those areas. We build useful service-area coverage and local signals instead of thin, duplicated city pages." },
      { question: "Should contractors use Local Services Ads?", answer: "They can be valuable for eligible categories, but lead quality, verification, response process, and economics should be reviewed alongside other channels." },
      { question: "How do we get more Google reviews?", answer: "The best system asks consistently after completed work, makes the process easy, trains the team, and responds professionally without incentives or review gating." },
      { question: "Can you track phone calls from marketing?", answer: "Yes. Call tracking can connect conversations with campaigns and pages, provided it is configured carefully so local business information stays consistent." },
      { question: "Will you target every service we offer?", answer: "We normally prioritize the services that fit capacity, profitability, seasonality, and real customer demand before expanding coverage." },
      { question: "How quickly can local marketing produce leads?", answer: "Paid channels may create feedback sooner, while maps and organic visibility usually build over time. Timing depends on competition, history, and the current foundation." },
    ],
    related: sharedRelated,
    ctaEyebrow: "Own more of your demand",
    ctaTitle: "See where local customers are",
    ctaAccent: "choosing someone else.",
    ctaBody: "Request a free audit and we will identify the profile, service-area, website, review, and campaign opportunities worth fixing first.",
  },
  "law-firm-marketing": {
    slug: "law-firm-marketing",
    shortName: "Law Firm Marketing",
    metadataTitle: "Law Firm Marketing Services | Rank It Globally",
    description: "SEO, paid search, content, and conversion strategy for law firms that need clearer visibility, stronger trust, and more qualified consultation opportunities.",
    theme: "legal",
    eyebrow: "Search visibility for law firms",
    heroLead: "Earn attention before",
    heroAccent: "the consultation begins.",
    heroBody: "We connect technical SEO, practice-area content, local search, paid demand, authority signals, and a clearer consultation path without relying on unsupported promises.",
    heroLabel: "Client decision path",
    heroSignals: ["Need", "Trust", "Consult"],
    heroOutcome: "More qualified consultation opportunities",
    challengeTitle: "Why capable firms remain",
    challengeAccent: "difficult to choose.",
    challengeBody: "Legal search is competitive, trust-sensitive, and often urgent. The website must demonstrate relevance and credibility before a prospect is ready to speak.",
    challenges: [
      { icon: "ads", title: "Advertising has constraints", body: "Policy, cost, and competition make broad targeting inefficient." },
      { icon: "pin", title: "Local competition is intense", body: "Maps visibility depends on a connected profile, website, and reputation system." },
      { icon: "ai", title: "AI changes discovery", body: "Clear, authoritative answers are increasingly important before a click occurs." },
      { icon: "reviews", title: "Trust decides the shortlist", body: "Prospects assess reviews, attorneys, evidence, and process before contacting a firm." },
      { icon: "content", title: "Practice pages are generic", body: "Thin pages fail to address jurisdiction, situation, process, and next-step questions." },
      { icon: "mobile", title: "The consultation path is unclear", body: "Slow pages and ambiguous calls to action reduce confidence." },
    ],
    servicesTitle: "A connected system for",
    servicesAccent: "qualified legal demand.",
    servicesBody: "Every service supports discovery, trust, or the path to a consultation.",
    services: [
      { icon: "pin", title: "Local legal search", body: "Strengthen profile, location, review, and website signals for relevant markets.", tags: ["Maps", "GBP", "Locations"] },
      { icon: "schema", title: "Technical SEO", body: "Improve crawlability, site architecture, performance, and structured data.", tags: ["Crawl", "Speed", "Schema"] },
      { icon: "content", title: "Practice-area content", body: "Build useful pages around legal intent, jurisdiction, process, and client questions.", tags: ["Services", "FAQs", "Internal links"] },
      { icon: "shield", title: "Authority development", body: "Present attorneys, experience, citations, and evidence with responsible language.", tags: ["E-E-A-T", "Profiles", "Editorial"] },
      { icon: "ads", title: "Paid search", body: "Capture selected high-intent queries while organic authority develops.", tags: ["Google Ads", "Landing pages", "Tracking"] },
      { icon: "cro", title: "Consultation conversion", body: "Make it easier for qualified prospects to understand fit and contact the firm.", tags: ["UX", "Forms", "Calls"] },
    ],
    workflowTitle: "From search audit to",
    workflowAccent: "clearer client acquisition.",
    workflowBody: "We prioritize technical and decision-path issues, then build coverage around the matters the firm is equipped to handle.",
    workflow: [
      { title: "Review the market", body: "Assess practice areas, locations, competitors, demand, and current lead quality." },
      { title: "Strengthen the foundation", body: "Improve technical health, information architecture, profiles, and measurement." },
      { title: "Build useful authority", body: "Create practice, location, and educational content that answers real questions." },
      { title: "Refine acquisition", body: "Use consultation quality and search behavior to guide budgets and expansion." },
    ],
    opportunitiesTitle: "Reach prospects across",
    opportunitiesAccent: "the decision journey.",
    opportunitiesBody: "Urgent matters, complex research, local comparisons, and referrals each require a different path into the firm.",
    opportunities: [
      { icon: "search", title: "Practice intent", body: "Match pages to the specific situations prospective clients search for." },
      { icon: "pin", title: "Local comparison", body: "Support location relevance and visible proof in maps and organic search." },
      { icon: "ads", title: "Immediate demand", body: "Use paid search selectively for high-priority matters and markets." },
      { icon: "cro", title: "Consultation clarity", body: "Help visitors understand fit, confidentiality, and what happens next." },
    ],
    proofTitle: "A credible system uses",
    proofAccent: "evidence over promises.",
    proofBody: "We focus reporting on relevant visibility, prospect behavior, and consultation quality rather than guaranteed outcomes.",
    proof: [
      { kicker: "Relevance", title: "Track the right searches", body: "Focus on matters, locations, and questions aligned with the firm's services." },
      { kicker: "Trust", title: "Review decision signals", body: "Assess engagement with attorneys, proof, process, and key service pages." },
      { kicker: "Quality", title: "Learn from consultations", body: "Use lead context to improve targeting, copy, and qualification." },
    ],
    audiences: ["Personal injury", "Family law", "Business law", "Estate planning", "Criminal defense", "Immigration", "Employment law"],
    faqs: [
      { question: "Do you guarantee a number of signed cases?", answer: "No. Case outcomes depend on the market, practice area, intake, reputation, eligibility, and many factors outside marketing. We improve visibility and the path to qualified consultations." },
      { question: "Can law firms run Google Ads?", answer: "Yes, subject to platform policy and local professional rules. Campaign structure and language need careful review, especially in sensitive legal categories." },
      { question: "What makes a practice-area page useful?", answer: "It should explain who the service is for, relevant situations, jurisdiction, process, questions, proof, and a clear next step without giving misleading legal advice." },
      { question: "Can you market multiple offices?", answer: "Yes. Each location needs accurate business information, real local relevance, distinct useful content, and consistent ownership across profiles and the website." },
      { question: "How do you measure law firm marketing?", answer: "We connect visibility and campaign behavior with qualified calls, forms, consultations, and feedback from intake where tracking is appropriate." },
      { question: "How do you handle legal advertising compliance?", answer: "We avoid guarantees and unsupported claims, but the firm remains responsible for reviewing marketing against applicable bar rules and legal requirements." },
    ],
    related: sharedRelated,
    ctaEyebrow: "Start with the evidence",
    ctaTitle: "See what limits your firm's",
    ctaAccent: "search visibility.",
    ctaBody: "Request a free audit and we will identify the technical, content, local, trust, and conversion opportunities worth addressing first.",
  },
  "real-estate-marketing": {
    slug: "real-estate-marketing",
    shortName: "Real Estate Marketing",
    metadataTitle: "Real Estate Marketing Services | Rank It Globally",
    description: "Local SEO, neighborhood content, paid campaigns, website strategy, and conversion systems for real estate professionals and property businesses.",
    theme: "real-estate",
    eyebrow: "Search-led real estate growth",
    heroLead: "Be visible where buyers and sellers",
    heroAccent: "research the next move.",
    heroBody: "We connect neighborhood search, IDX architecture, local visibility, paid campaigns, authority content, and clearer consultation paths.",
    heroLabel: "Property discovery path",
    heroSignals: ["Market", "Property", "Advisor"],
    heroOutcome: "More direct buyer and seller conversations",
    challengeTitle: "Why many real estate sites",
    challengeAccent: "generate little direct demand.",
    challengeBody: "Listings alone rarely build durable visibility. Search engines and visitors need useful local context, technical clarity, and a reason to trust the advisor behind the inventory.",
    challenges: [
      { icon: "pin", title: "Neighborhood intent is missed", body: "High-value local searches are often left to portals and competitors." },
      { icon: "schema", title: "IDX creates technical noise", body: "Duplicate URLs, weak indexing, and slow templates can dilute important pages." },
      { icon: "profile", title: "Local profiles are incomplete", body: "Missing categories, reviews, and location connections reduce direct discovery." },
      { icon: "search", title: "Portals dominate results", body: "Listing platforms capture demand that could be supported by local expertise." },
      { icon: "content", title: "Neighborhood content is thin", body: "Generic pages do not answer how people compare places, prices, and lifestyles." },
      { icon: "community", title: "Referral-only growth has a ceiling", body: "A strong network benefits from an owned discovery system that works between referrals." },
    ],
    servicesTitle: "Build visibility around",
    servicesAccent: "markets and decisions.",
    servicesBody: "The strategy connects property search with neighborhood expertise and an easy route to a conversation.",
    services: [
      { icon: "pin", title: "Neighborhood SEO", body: "Build market, neighborhood, and service coverage around real search demand.", tags: ["Local SEO", "Areas", "Maps"] },
      { icon: "content", title: "Area guides", body: "Create useful pages about lifestyle, property types, process, and local considerations.", tags: ["Guides", "Questions", "Internal links"] },
      { icon: "schema", title: "IDX architecture", body: "Clarify which pages should be indexed and how listings connect to owned content.", tags: ["Technical SEO", "Templates", "Speed"] },
      { icon: "ads", title: "Buyer and seller campaigns", body: "Use search and social campaigns with focused offers and landing pages.", tags: ["Google", "Meta", "Lead quality"] },
      { icon: "shield", title: "Market authority", body: "Show expertise through useful updates, profiles, case context, and proof.", tags: ["E-E-A-T", "Content", "Reputation"] },
      { icon: "cro", title: "Consultation conversion", body: "Improve property inquiry, valuation, and advisor-contact journeys.", tags: ["UX", "Forms", "Calls"] },
    ],
    workflowTitle: "From market audit to",
    workflowAccent: "owned local demand.",
    workflowBody: "We separate listing inventory from durable search assets, then connect both to a clearer lead journey.",
    workflow: [
      { title: "Map demand", body: "Review markets, services, property types, audiences, portals, and current visibility." },
      { title: "Fix the structure", body: "Improve IDX behavior, site architecture, local profiles, speed, and tracking." },
      { title: "Build local depth", body: "Create useful neighborhood, buyer, seller, and market content." },
      { title: "Expand and refine", body: "Use inquiries and search behavior to prioritize markets and campaigns." },
    ],
    opportunitiesTitle: "Support more than",
    opportunitiesAccent: "one kind of property search.",
    opportunitiesBody: "Buyer research, seller valuation, relocation, investment, and property management each need a distinct message and conversion path.",
    opportunities: [
      { icon: "search", title: "Neighborhood research", body: "Answer how people compare areas before they choose an advisor." },
      { icon: "content", title: "Seller education", body: "Explain valuation, preparation, timing, and the sales process." },
      { icon: "ads", title: "Campaign demand", body: "Promote specific markets and offers without sending everyone to the homepage." },
      { icon: "cro", title: "Inquiry confidence", body: "Make the next step relevant to the visitor's property goal." },
    ],
    proofTitle: "Build an asset beyond",
    proofAccent: "the listing feed.",
    proofBody: "We track whether local expertise, useful pages, and campaigns create more direct, relevant conversations.",
    proof: [
      { kicker: "Markets", title: "See where demand develops", body: "Compare visibility and engagement across priority neighborhoods and services." },
      { kicker: "Intent", title: "Understand the visitor", body: "Separate buyer, seller, relocation, investment, and general browsing behavior." },
      { kicker: "Leads", title: "Improve the conversation", body: "Use inquiry quality to refine pages, offers, and campaign targeting." },
    ],
    audiences: ["Agents", "Brokerages", "Developers", "Property managers", "Investment firms", "Commercial real estate"],
    faqs: [
      { question: "Can you work with an IDX website?", answer: "Yes. We review how IDX pages are generated, indexed, linked, and experienced, then build owned local content around the inventory rather than relying on it alone." },
      { question: "Can one website target many neighborhoods?", answer: "Yes, when each page provides genuinely useful local context and supports a real service area. Thin or duplicated neighborhood pages are not the goal." },
      { question: "Do you generate buyer and seller leads?", answer: "We build visibility and conversion paths for both, but lead volume and quality depend on the market, offer, reputation, competition, and follow-up process." },
      { question: "Should real estate professionals use paid social?", answer: "It can support awareness, retargeting, and specific offers. It works best when creative and landing pages match the audience and market rather than using generic listing promotion." },
      { question: "How do you compete with major property portals?", answer: "We focus on local expertise, specific intent, useful decision content, and direct advisor relationships rather than trying to reproduce a national portal." },
      { question: "Can you improve an existing brokerage website?", answer: "Yes. We can prioritize technical, content, local, performance, and conversion improvements before recommending a larger rebuild." },
    ],
    related: sharedRelated,
    ctaEyebrow: "Own more local discovery",
    ctaTitle: "See where buyer and seller demand is",
    ctaAccent: "passing you by.",
    ctaBody: "Request a free audit and we will review market coverage, IDX structure, local visibility, content, and the path to an inquiry.",
  },
  "tech-startup-marketing": {
    slug: "tech-startup-marketing",
    shortName: "Tech Startup Marketing",
    metadataTitle: "Tech Startup Marketing Services | Rank It Globally",
    description: "SEO, content, authority, conversion, and paid growth systems for SaaS and technology startups building durable demand beyond paid acquisition.",
    theme: "technology",
    eyebrow: "Organic growth for technology",
    heroLead: "Turn product knowledge into",
    heroAccent: "discoverable demand.",
    heroBody: "We connect technical SEO, category positioning, problem-led content, authority, conversion, and paid learning so startups can build an owned acquisition system.",
    heroLabel: "Startup demand system",
    heroSignals: ["Problem", "Category", "Product"],
    heroOutcome: "A clearer route from search to signup",
    challengeTitle: "The growth traps that make",
    challengeAccent: "acquisition fragile.",
    challengeBody: "Early growth often depends on paid campaigns and founder networks. Durable demand requires clear positioning, technical foundations, useful content, and conversion paths built for evaluation.",
    challenges: [
      { icon: "ads", title: "Paid media carries the pipeline", body: "Acquisition becomes vulnerable when every new visit must be purchased." },
      { icon: "search", title: "Keywords do not match the stage", body: "Broad high-volume terms can attract readers who are nowhere near product fit." },
      { icon: "content", title: "The blog does not create action", body: "Unconnected articles educate without guiding visitors toward the product." },
      { icon: "shield", title: "The domain lacks authority", body: "Strong product thinking remains invisible without evidence, references, and earned attention." },
      { icon: "schema", title: "Technical debt blocks growth", body: "Rendering, architecture, migrations, and weak templates can undermine otherwise good content." },
      { icon: "ai", title: "AI systems lack clear context", body: "Vague category language makes the company difficult to understand and cite." },
    ],
    servicesTitle: "A full-funnel system for",
    servicesAccent: "technical buyers.",
    servicesBody: "The work connects product positioning, discovery, evaluation, and the action that matters to the business.",
    services: [
      { icon: "strategy", title: "Stage-aware keyword map", body: "Prioritize problems, use cases, categories, alternatives, and integrations around real product fit.", tags: ["ICP", "Intent", "Positioning"] },
      { icon: "content", title: "Conversion content", body: "Build pages and articles that move readers from a problem toward a relevant product action.", tags: ["Use cases", "Comparisons", "Guides"] },
      { icon: "schema", title: "Technical foundations", body: "Improve rendering, architecture, performance, indexation, and scalable templates.", tags: ["Technical SEO", "Programmatic", "Web"] },
      { icon: "shield", title: "Authority development", body: "Earn references through original insight, useful assets, partnerships, and distribution.", tags: ["Digital PR", "Research", "Links"] },
      { icon: "cro", title: "Signup conversion", body: "Clarify value, proof, objections, and next steps across the website journey.", tags: ["UX", "Testing", "Activation"] },
      { icon: "ads", title: "Paid learning loops", body: "Use campaigns to test messages and capture demand while organic coverage grows.", tags: ["Search", "Social", "Landing pages"] },
    ],
    workflowTitle: "From product context to",
    workflowAccent: "an owned growth engine.",
    workflowBody: "We begin with market and product reality, then build the technical and editorial system around a focused growth thesis.",
    workflow: [
      { title: "Map product and market", body: "Clarify ICP, category, use cases, competitors, objections, and the conversion event." },
      { title: "Fix the foundation", body: "Resolve technical blockers and connect the site's information architecture." },
      { title: "Build useful coverage", body: "Publish product, comparison, integration, use-case, and educational assets." },
      { title: "Distribute and refine", body: "Use sales feedback, search behavior, campaigns, and activation data to improve." },
    ],
    opportunitiesTitle: "Meet technical buyers across",
    opportunitiesAccent: "the evaluation journey.",
    opportunitiesBody: "Different pages serve different jobs: understanding the problem, defining the category, comparing approaches, validating fit, and taking action.",
    opportunities: [
      { icon: "search", title: "Problem discovery", body: "Answer the operational questions buyers search before they know a category." },
      { icon: "content", title: "Product evaluation", body: "Support use cases, integrations, alternatives, and implementation questions." },
      { icon: "ai", title: "Machine clarity", body: "Use consistent entities, schema, and answer-ready content across the site." },
      { icon: "cro", title: "Signup confidence", body: "Connect proof and product context with an appropriate next step." },
    ],
    proofTitle: "Make growth decisions with",
    proofAccent: "product context.",
    proofBody: "Reporting should connect visibility with pipeline quality, signup behavior, and what sales or product teams are learning.",
    proof: [
      { kicker: "Demand", title: "Track category development", body: "Monitor relevant discovery across problems, categories, competitors, and product terms." },
      { kicker: "Journey", title: "Connect content to action", body: "Review how visitors move from education into evaluation and signup paths." },
      { kicker: "Feedback", title: "Learn across teams", body: "Use sales objections, activation, and campaign learning to improve the next cycle." },
    ],
    audiences: ["SaaS", "AI products", "Developer tools", "B2B platforms", "Fintech", "Health tech", "Marketplaces"],
    faqs: [
      { question: "When should a startup invest in SEO?", answer: "SEO becomes useful when the product, market, and audience are clear enough to build focused pages. Earlier technical and positioning work can prevent expensive rework later." },
      { question: "Can SEO support a new category?", answer: "Yes, but it requires a mix of existing problem demand, category education, product language, authority, and distribution. Search volume alone should not define the strategy." },
      { question: "Do you work with product-led growth companies?", answer: "Yes. We connect content and landing pages with trials, demos, templates, product experiences, and the activation journey that makes sense for the business." },
      { question: "Can paid campaigns and SEO share a strategy?", answer: "They should. Paid campaigns can test messages and capture demand while SEO builds durable coverage; search and conversion data can improve both." },
      { question: "What content should a SaaS company publish?", answer: "The mix usually includes problem education, use cases, integrations, comparisons, implementation guidance, product pages, and original insights aligned with the buyer journey." },
      { question: "How do you measure startup content?", answer: "We look at relevant visibility, engagement, assisted journeys, conversion actions, lead quality, and product feedback rather than treating raw traffic as the goal." },
    ],
    related: sharedRelated,
    ctaEyebrow: "Build beyond rented demand",
    ctaTitle: "See what is limiting your",
    ctaAccent: "organic growth system.",
    ctaBody: "Request a free audit and we will review technical health, positioning, content coverage, authority, and the route from discovery to signup.",
  },
};
